services:
  mysql:
    image: mysql:latest
    environment:
      - 'MYSQL_DATABASE=spring_db'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'