spring:
  application:
    name: week1-commerce

  datasource:
    url: jdbc:mysql://localhost:3306/commerce
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: false  # Flyway 비활성화 (현재는 ddl-auto: create 사용)
#    # 마이그레이션 파일 위치 지정 (기본값)
#    locations: classpath:db/migration
#    default-schema: commerce

# Swagger UI 설정 (Springdoc)
springdoc:
  swagger-ui:
    enabled: true

server:
  port: 8080