spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10  # 최대 커넥션 개수
      connection-timeout: 30000 # 커넥션을 얻기 위해 대기하는 최대 시간 (ms)
      max-lifetime: 1800000 # 커넥션의 최대 수명 (ms)

  flyway:
    enabled: true # Flyway 활성화
    # clean-disabled: false   # 기본 true라 clean 막혀 있음. 개발에서만 false
    # 마이그레이션 파일 위치 지정 (기본값)
    locations: classpath:db/migration
    baseline-on-migrate: true # 기존에 테이블이 있는 DB에 Flyway를 처음 적용할 때 사용

  # JPA 및 Hibernate 설정
  jpa:
    hibernate:
      # ddl-auto: 애플리케이션 실행 시 스키마 처리 전략
      # none: 아무 작업도 하지 않음 (운영 환경)
      # create: 기존 테이블 삭제 후 생성
      # update: 변경된 부분만 반영
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true       # 보기 좋게 포맷
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    # Hibernate가 실행하는 SQL 쿼리를 DEBUG 레벨로 로그에 출력
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE       # 바인딩된 파라미터 값
    org.hibernate.orm.jdbc.extract: TRACE    # ResultSet에서 꺼낸 값(조회 결과)
    com.example.stproject.domain: DEBUG
# Swagger UI 설정 (Springdoc)
springdoc:
  swagger-ui:
    enabled: true

server:
  port: 8080