spring:

  # flyway ??
  flyway:
    enabled: true # Flyway ???
    # ?????? ?? ?? ?? (???) classpath: resource ????
    locations: classpath:db/migration
  #    baseline-on-migrate: true # ??? ???? ?? DB? Flyway? ?? ??? ? ??

  # ?????? ?? ??
  datasource:
    url: jdbc:mysql://localhost:3306/spring_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10 # ?? ??? ??
      connection-timeout: 3000 # ???? ?? ?? ???? ?? ??
      max-lifetime: 1800000 # ???? ?? ?? (ms)

  # JPA ? Hibernate ??
  jpa:
    hibernate:
      # ddl-auto: ?????? ?? ? ???(???) ?? ??
      # none: ?? ??? ?? ?? (?? ?? ??)
      # create: ?? ??? ?? ? ?? ??
      # update: ??? ??? ??
      ddl-auto: validate
    properties:
      hibernate:
        # MySQL 8 ??? ?? Dialect(??) ??
        dialect: org.hibernate.dialect.MySQL8Dialect

# ?? ?? ??
logging:
  level:
    # Hibernate? ???? SQL ??? DEBUG ??? ??? ??
    org.hibernate.SQL: DEBUG

# ?? ? ?? ??
server:
  port: 8080