spring:
  application:
    name: project1

  flyway:
    enabled: true
    locations: classpath:db/migration # ?????? SQL ??? ??? ??
    baseline-on-migrate: true # ??? ???? ?? DB? Flyway? ?? ??? ? ??

  datasource:
    url: jdbc:mysql://localhost:3306/spring_db
    username: root
    password: password
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


# ?? ?? ??
logging:
  level:
    # Hibernate? ???? SQL ??? DEBUG ??? ??? ??
    org.hibernate.SQL: DEBUG

server:
  port: 8080
