

spring:
  flyway:
    enabled: true # Flyway ???
    # ?????? ?? ?? ?? (???)
    locations: classpath:db/migration

  logging:
    level:
      root: info               # 루트는 INFO
      com.example.demo: debug  # 내가 만든 패키지는 DEBUG 로
  # ?????? ?? ??
  datasource:
    url: jdbc:mysql://localhost:3306/spring_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
        enabled: false

  # JPA ? Hibernate ??
  jpa:
    hibernate:
      # ddl-auto: ?????? ?? ? ???(???) ?? ??
      # none: ?? ??? ?? ?? (?? ?? ??)
      # create: ?? ??? ?? ? ?? ??
      # update: ??? ??? ??
      ddl-auto: validate
    properties:
      hibernate:
        # MySQL 8 ??? ?? Dialect(??) ??
        dialect: org.hibernate.dialect.MySQL8Dialect

# ?? ?? ??
logging:
  level:
    # Hibernate? ???? SQL ??? DEBUG ??? ??? ??
    org.hibernate.SQL: DEBUG

# ?? ? ?? ??
server:
  port: 8082

monitoring:
  slow-threshold-ms: 400 # ExecutionTimeAspect warns when service methods exceed this value
