spring:
  application:
    name: demo1
  datasource:
    url: jdbc:mysql://localhost:3307/spring_db_week1?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      jakarta:
#        persistence:
#          schema-generation:
#            scripts:
#              action: none   # create | drop-and-create | none
#              create-target: ./target/schema.sql
#            database:
#              action: create
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true # SQL ???
        highlight_sql: true # ANSI ??? ?? ????
        use_sql_comments: true # SQL ??? /* */ ?? ??
      hibernate.transaction.jta.platform: org.hibernate.service.jta.JtaPlatform

server:
  port: 8080
logging:
  include-application-group: false
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.tool.schema: debug