spring:
  application:
    name: ecommerce

  # ?????? ?? ??
  datasource:
    url: jdbc:mysql://localhost:3305/spring_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA ? Hibernate ??
  jpa:
    hibernate:
      # ddl-auto: ?????? ?? ? ???(???) ?? ??
      # none: ?? ??? ?? ?? (?? ?? ??)
      # create: ?? ??? ?? ? ?? ??
      # update: ??? ??? ??
      ddl-auto: update
    properties:
      hibernate:
        # MySQL 8 ??? ?? Dialect(??) ??
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true # Flyway ???
    # ?????? ?? ?? ?? (???)
    locations: classpath:db/migration

# ?? ?? ??
logging:
  level:
    # Hibernate? ???? SQL ??? DEBUG ??? ??? ??
    org.hibernate.SQL: DEBUG

# ?? ? ?? ??
server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true