# .properties 예시와 동일한 설정입니다.
spring:
  flyway:
    enabled: true # Flyway 활성화
    # 마이그레이션 파일 위치 지정 (기본값)
    locations: classpath:db/migration
  datasource:
    url: jdbc:mysql://localhost:3306/spring_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:

  # JPA 및 Hibernate 설정
  jpa:
    hibernate:
      # ddl-auto: 애플리케이션 실행 시 스키마(테이블) 처리 전략
      # none: 아무 작업도 하지 않음 (운영 환경 추천)
      # create: 기존 테이블 삭제 후 다시 생성
      # update: 변경된 부분만 반영
      ddl-auto: none
    properties:
      hibernate:
        # MySQL 8 버전에 맞는 Dialect(방언) 설정
        dialect: org.hibernate.dialect.MySQL8Dialect
  
  # Swagger UI 설정 (Springdoc)
  springdoc:
    swagger-ui:
      enabled: true

server:
  port: 8080